### ISSUE TITLE
dbdcフォルダのエラー

### ISSUE THREAD

**Issue by JUNICHIRO-SUZUKI** [dsbook/dsbook#11]
教科書p.168
dbdc_data_converter.pyを実行して、dbdc_bertフォルダを作成してチューニングしたところ
Traceback (most recent call last):
  File "transformers/examples/run_glue.py", line 541, in <module>
    main()
  File "transformers/examples/run_glue.py", line 492, in main
    global_step, tr_loss = train(args, train_dataset, model, tokenizer)
  File "transformers/examples/run_glue.py", line 87, in train
    train_sampler = RandomSampler(train_dataset) if args.local_rank == -1 else DistributedSampler(train_dataset)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/sampler.py", line 94, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0
このようなエラーが出てしまい実行できないのですが、どうすればよいでしょうか？

**Comment by 1never** [comment]
データ数が0であるというエラーが出ています．
dbdc_bertフォルダ内のtrain.tsvとdev.tsvをエディタで開いて，きちんと作成できているか確認をお願いします．
