### ISSUE TITLE
「 python3 echo_system.py」コマンドの実行が正常に動作しない

### ISSUE THREAD

**Issue by hirokore** [dsbook/dsbook#12]
以下件、ご確認頂きたく。

■環境
ホストOS：windows 10
実行OS　：Ubuntu 18.04
python 　：3.6.9

■実施済みコマンド（history）
    1  sudo apt update
    2  sudo apt install git -y
    3  cd
    4  ll
    5  git clone https://github.com/dsbook/dsbook,git
    6  git clone https://github.com/dsbook/dsbook.git
    7  cd dsbook/
    8  ls
    9  explorer.exe .
   10  python3 -v
   11  python3 -V
   12  sudo apt install python3-pip -y
   13  sudo apt install mecab libmecab-dev mecab-ipadic-utf8 swig -y
   14  pip3 install mecab-python3==0.996.5
   15  python3 mecab-python3_test.py
   16  ls -ltr
   17  vi telegram_bot.py
   18  pip3 install python-telegram-bot
   19  python3 echo_system.py
   20  history

■エラー内容
①は初回のみ、②は二回目以降のエラー内容、telegram上で文字を打つたびに発報

①Traceback (most recent call last):
  File "/home/yamashita/.local/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 402, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/yamashita/.local/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 398, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 311, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 272, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yamashita/.local/lib/python3.6/site-packages/telegram/utils/request.py", line 230, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/home/yamashita/.local/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 70, in request
    **urlopen_kw)
  File "/home/yamashita/.local/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/yamashita/.local/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/yamashita/.local/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 666, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/yamashita/.local/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/yamashita/.local/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/yamashita/.local/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "/home/yamashita/.local/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 405, in _make_request
    exc_cls=ReadTimeoutError)
  File "/home/yamashita/.local/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 321, in _raise_timeout
    raise exc_cls(*args)
telegram.vendor.ptb_urllib3.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=5.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "echo_system.py", line 19, in <module>
    bot.run()
  File "/home/yamashita/dsbook/telegram_bot.py", line 33, in run
    updater.start_polling()
  File "/home/yamashita/.local/lib/python3.6/site-packages/telegram/ext/updater.py", line 272, in start_polling
    self._init_thread(self.dispatcher.start, "dispatcher", ready=dispatcher_ready)
  File "/home/yamashita/.local/lib/python3.6/site-packages/telegram/ext/updater.py", line 215, in _init_thread
    name="Bot:{}:{}".format(self.bot.id, name),
  File "/home/yamashita/.local/lib/python3.6/site-packages/telegram/bot.py", line 62, in decorator
    self.get_me()
  File "<decorator-gen-1>", line 2, in get_me
  File "/home/yamashita/.local/lib/python3.6/site-packages/telegram/bot.py", line 78, in decorator
    result = func(*args, **kwargs)
  File "/home/yamashita/.local/lib/python3.6/site-packages/telegram/bot.py", line 326, in get_me
    result = self._post('getMe', timeout=timeout, api_kwargs=api_kwargs)
  File "/home/yamashita/.local/lib/python3.6/site-packages/telegram/bot.py", line 185, in _post
    timeout=timeout)
  File "/home/yamashita/.local/lib/python3.6/site-packages/telegram/utils/request.py", line 328, in post
    **urlopen_kwargs)
  File "/home/yamashita/.local/lib/python3.6/site-packages/telegram/utils/request.py", line 232, in _request_wrapper
    raise TimedOut()
telegram.error.TimedOut: Timed out

②Traceback (most recent call last):
  File "/home/yamashita/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 425, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/yamashita/.local/lib/python3.6/site-packages/telegram/ext/handler.py", line 145, in handle_update
    return self.callback(update, context)
  File "/home/yamashita/dsbook/telegram_bot.py", line 20, in message
    input = {'utt': update.message.text, 'sessionId': str(update.message.from_user.id)}
AttributeError: 'CallbackContext' object has no attribute 'message'

■他
・上記環境で本書のコマンド通りに進めていたが
「 python3 echo_system.py」コマンドを実行してもtelegramで応答がない状況

・上記実施コマンド以外ではtelegramのインストールとbotfatherによるTOKENの生成を実施

**Comment by 1never** [comment]
python-telegram-botのバージョンアップにより，動作しなくなったことを確認いたしました．
バージョン指定してインストールすれば動きましたので，以下を実行してください．

$ pip3 install python-telegram-bot==12.8

**Comment by hirokore** [comment]
＞1never殿
迅速にご対応頂きありがとうございます。
以下コマンドで無事、動作したことを確認いたしました。

■対応コマンド
$ pip3 install python-telegram-bot==12.8

■結果
/home/yamashita/dsbook/telegram_bot.py:29: TelegramDeprecationWarning: Old Handler API is deprecated - see https://git.io/fxJuV for details
  updater = Updater(TOKEN)
