### ISSUE TITLE
プログラムエラー

### ISSUE THREAD

**Issue by Sakura972016** [dsbook/dsbook#13]
書籍内の
python3 echo_system.py
のコードを実行したときに
Traceback (most recent call last):
  File "echo_system.py", line 19, in <module>
    bot.run()
  File "/home/sakura-yuki9720/dsbook/telegram_bot.py", line 29, in run
    updater = Updater(TOKEN)
  File "/home/sakura-yuki9720/.local/lib/python3.6/site-packages/telegram/ext/updater.py", line 165, in __init__
    defaults=defaults)
  File "/home/sakura-yuki9720/.local/lib/python3.6/site-packages/telegram/bot.py", line 130, in __init__
    self.token = self._validate_token(token)
  File "/home/sakura-yuki9720/.local/lib/python3.6/site-packages/telegram/bot.py", line 197, in _validate_token
    raise InvalidToken()
telegram.error.InvalidToken: Invalid token
というエラーが発生しました。
$pip3 install python-telegram-bot==12.8)
のコマンドを試した後ですが動きませんでした。
どうすれば動くようになるか、対応のほどよろしくお願いいたします。

**Comment by 1never** [comment]
Invalid token，つまりtelegram_bot.pyのアクセストークンが不正であるというエラーです．
コピーペーストをミスしている可能性がありますので，確認してください．

**Comment by Sakura972016** [comment]
C:\Users\81802\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\LocalState\rootfs\home\sakura-yuki9720\dsbook
のtelegram_bot.pyでコピーペーストして再度試しましたが治りませんでした。
その後も新しくtelegramでnewbotを作って同じように試しましたが治りませんでした。
使っているファイルが間違っている等であればファイルの場所等も教えてください
