### ISSUE TITLE
Eiasticsearchが起動できません。

### ISSUE THREAD

**Issue by osuro33** [dsbook/dsbook#16]
Eiastcsearchを書籍通りにダウンロードしましたが、起動しません。
./bin/elasticsearch
を入力してもプログラムが終了してしまいます。
お手数をおかけいたしますが、ご返信をお待ちしております。
よろしくお願いいたします。

**Comment by osuro33** [comment]
以下のように出力され、プログラムが終了してしまいます。
dsbook/elasticsearch-7.5.1$ ./bin/elasticsearch
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[2020-11-17T00:14:04,136][WARN ][o.e.b.JNANatives         ] [DESKTOP-BO88V3F] unable to install syscall filter:
java.lang.UnsupportedOperationException: seccomp unavailable: CONFIG_SECCOMP not compiled into kernel, CONFIG_SECCOMP and CONFIG_SECCOMP_FILTER are needed
        at org.elasticsearch.bootstrap.SystemCallFilter.linuxImpl(SystemCallFilter.java:342) ~[elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.bootstrap.SystemCallFilter.init(SystemCallFilter.java:617) ~[elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.bootstrap.JNANatives.tryInstallSystemCallFilter(JNANatives.java:260) [elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.bootstrap.Natives.tryInstallSystemCallFilter(Natives.java:113) [elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:110) [elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:172) [elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) [elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) [elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) [elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125) [elasticsearch-cli-7.5.1.jar:7.5.1]
        at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-7.5.1.jar:7.5.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) [elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) [elasticsearch-7.5.1.jar:7.5.1]
[2020-11-17T00:14:05,169][INFO ][o.e.e.NodeEnvironment    ] [DESKTOP-BO88V3F] using [1] data paths, mounts [[/ (rootfs)]], net usable_space [574.5gb], net total_space [611.8gb], types [wslfs]
[2020-11-17T00:14:05,192][INFO ][o.e.e.NodeEnvironment    ] [DESKTOP-BO88V3F] heap size [1007.3mb], compressed ordinary object pointers [true]
[2020-11-17T00:14:05,229][INFO ][o.e.n.Node               ] [DESKTOP-BO88V3F] node name [DESKTOP-BO88V3F], node ID [Ey8YJ7LrTJ6DiHakMIItTA], cluster name [elasticsearch]
[2020-11-17T00:14:05,243][INFO ][o.e.n.Node               ] [DESKTOP-BO88V3F] version[7.5.1], pid[1759], build[default/tar/3ae9ac9a93c95bd0cdc054951cf95d88e1e18d96/2019-12-16T22:57:37.835892Z], OS[Linux/4.4.0-18362-Microsoft/amd64], JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/13.0.1/13.0.1+9]
[2020-11-17T00:14:05,257][INFO ][o.e.n.Node               ] [DESKTOP-BO88V3F] JVM home [/home/osuro/dsbook/elasticsearch-7.5.1/jdk]
[2020-11-17T00:14:05,265][INFO ][o.e.n.Node               ] [DESKTOP-BO88V3F] JVM arguments [-Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=COMPAT, -Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -Djava.io.tmpdir=/tmp/elasticsearch-11295553479343300926, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -XX:MaxDirectMemorySize=536870912, -Des.path.home=/home/osuro/dsbook/elasticsearch-7.5.1, -Des.path.conf=/home/osuro/dsbook/elasticsearch-7.5.1/config, -Des.distribution.flavor=default, -Des.distribution.type=tar, -Des.bundled_jdk=true]
[2020-11-17T00:14:17,986][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [aggs-matrix-stats]
[2020-11-17T00:14:17,993][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [analysis-common]
[2020-11-17T00:14:18,002][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [flattened]
[2020-11-17T00:14:18,008][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [frozen-indices]
[2020-11-17T00:14:18,018][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [ingest-common]
[2020-11-17T00:14:18,025][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [ingest-geoip]
[2020-11-17T00:14:18,034][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [ingest-user-agent]
[2020-11-17T00:14:18,042][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [lang-expression]
[2020-11-17T00:14:18,052][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [lang-mustache]
[2020-11-17T00:14:18,060][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [lang-painless]
[2020-11-17T00:14:18,070][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [mapper-extras]
[2020-11-17T00:14:18,078][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [parent-join]
[2020-11-17T00:14:18,087][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [percolator]
[2020-11-17T00:14:18,094][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [rank-eval]
[2020-11-17T00:14:18,106][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [reindex]
[2020-11-17T00:14:18,116][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [repository-url]
[2020-11-17T00:14:18,124][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [search-business-rules]
[2020-11-17T00:14:18,135][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [spatial]
[2020-11-17T00:14:18,142][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [transform]
[2020-11-17T00:14:18,153][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [transport-netty4]
[2020-11-17T00:14:18,161][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [vectors]
[2020-11-17T00:14:18,172][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [x-pack-analytics]
[2020-11-17T00:14:18,183][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [x-pack-ccr]
[2020-11-17T00:14:18,193][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [x-pack-core]
[2020-11-17T00:14:18,202][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [x-pack-deprecation]
[2020-11-17T00:14:18,209][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [x-pack-enrich]
[2020-11-17T00:14:18,219][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [x-pack-graph]
[2020-11-17T00:14:18,227][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [x-pack-ilm]
[2020-11-17T00:14:18,239][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [x-pack-logstash]
[2020-11-17T00:14:18,251][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [x-pack-ml]
[2020-11-17T00:14:18,260][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [x-pack-monitoring]
[2020-11-17T00:14:18,271][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [x-pack-rollup]
[2020-11-17T00:14:18,272][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [x-pack-security]
[2020-11-17T00:14:18,273][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [x-pack-sql]
[2020-11-17T00:14:18,274][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [x-pack-voting-only-node]
[2020-11-17T00:14:18,283][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded module [x-pack-watcher]
[2020-11-17T00:14:18,295][INFO ][o.e.p.PluginsService     ] [DESKTOP-BO88V3F] loaded plugin [analysis-kuromoji]
[2020-11-17T00:14:31,496][INFO ][o.e.x.s.a.s.FileRolesStore] [DESKTOP-BO88V3F] parsed [0] roles from file [/home/osuro/dsbook/elasticsearch-7.5.1/config/roles.yml]
[2020-11-17T00:14:33,799][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [DESKTOP-BO88V3F] [controller/1852] [Main.cc@110] controller (64 bit): Version 7.5.1 (Build ae3c3c51b849be) Copyright (c) 2019 Elasticsearch BV
[2020-11-17T00:14:34,365][DEBUG][o.e.a.ActionModule       ] [DESKTOP-BO88V3F] Using REST wrapper from plugin org.elasticsearch.xpack.security.Security
[2020-11-17T00:14:34,707][INFO ][o.e.d.DiscoveryModule    ] [DESKTOP-BO88V3F] using discovery type [zen] and seed hosts providers [settings]
[2020-11-17T00:14:36,719][INFO ][o.e.n.Node               ] [DESKTOP-BO88V3F] initialized
[2020-11-17T00:14:36,720][INFO ][o.e.n.Node               ] [DESKTOP-BO88V3F] starting ...
[2020-11-17T00:14:37,096][INFO ][o.e.t.TransportService   ] [DESKTOP-BO88V3F] publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}
[2020-11-17T00:14:37,113][ERROR][o.e.g.GatewayMetaState   ] [DESKTOP-BO88V3F] failed to read or upgrade local state, exiting...
java.io.IOException: failed to find global metadata [generation: 20]
        at org.elasticsearch.gateway.MetaStateService.loadFullState(MetaStateService.java:87) ~[elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.gateway.GatewayMetaState.upgradeMetaData(GatewayMetaState.java:154) [elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.gateway.GatewayMetaState.start(GatewayMetaState.java:90) [elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.node.Node.start(Node.java:696) [elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:273) [elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:358) [elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) [elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) [elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125) [elasticsearch-cli-7.5.1.jar:7.5.1]
        at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-7.5.1.jar:7.5.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) [elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) [elasticsearch-7.5.1.jar:7.5.1]
[2020-11-17T00:14:37,217][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [DESKTOP-BO88V3F] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: ElasticsearchException[failed to load metadata]; nested: IOException[failed to find global metadata [generation: 20]];
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125) ~[elasticsearch-cli-7.5.1.jar:7.5.1]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.5.1.jar:7.5.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) ~[elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.5.1.jar:7.5.1]
Caused by: org.elasticsearch.ElasticsearchException: failed to load metadata
        at org.elasticsearch.gateway.GatewayMetaState.start(GatewayMetaState.java:93) ~[elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.node.Node.start(Node.java:696) ~[elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:273) ~[elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:358) ~[elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.5.1.jar:7.5.1]
        ... 6 more
Caused by: java.io.IOException: failed to find global metadata [generation: 20]
        at org.elasticsearch.gateway.MetaStateService.loadFullState(MetaStateService.java:87) ~[elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.gateway.GatewayMetaState.upgradeMetaData(GatewayMetaState.java:154) ~[elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.gateway.GatewayMetaState.start(GatewayMetaState.java:90) ~[elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.node.Node.start(Node.java:696) ~[elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:273) ~[elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:358) ~[elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.5.1.jar:7.5.1]
        ... 6 more
[2020-11-17T00:14:37,397][INFO ][o.e.n.Node               ] [DESKTOP-BO88V3F] stopping ...
[2020-11-17T00:14:37,443][INFO ][o.e.n.Node               ] [DESKTOP-BO88V3F] stopped
[2020-11-17T00:14:37,448][INFO ][o.e.n.Node               ] [DESKTOP-BO88V3F] closing ...
[2020-11-17T00:14:37,479][INFO ][o.e.n.Node               ] [DESKTOP-BO88V3F] closed
[2020-11-17T00:14:37,489][INFO ][o.e.x.m.p.NativeController] [DESKTOP-BO88V3F] Native controller process has stopped - no new native processes can be started

**Comment by masahiro-mi** [comment]
（おそらく過去の）ステータスファイルを読み込むことができない，というエラーが発生しております．
[2020-11-17T00:14:37,113][ERROR][o.e.g.GatewayMetaState ] [DESKTOP-BO88V3F] failed to read or upgrade local state, exiting...

過去にElasticsearchをインストールしていたり，新たにElasticsearchをインストールされましたでしょうか？
（P134のElasticserchがインストールできない #7 にて，Elasticsearchのダウンロードまでは完了しているご様子です）
過去のElasticsearchと同じバージョンに戻すか，過去のElasticsearchのデータを削除することで，起動可能になるかと思います．

**Comment by osuro33** [comment]
Elasticserchが2つダウンロードされていました。片方を消すことで解決できました。
ご回答ありがとうごさいます。
