### ISSUE TITLE
Elasticsearchで接続に関するエラーが発生する

### ISSUE THREAD

**Issue by ikuhiroo** [dsbook/dsbook#17]
* 概要 
`python insert.pt` を実行すると、`ReadTimeoutError` が発生する。
エラー解決のためのアドバイスを頂きたいです。

* やったこと
    * Elasticsearchをデーモン起動する
    * 以下のコードブロックを実行し、`True`が返ってくることを確認
    *  `insert.py` を実行し、Elasticsearchにデータを格納（ここでエラー）
```
from elasticsearch import Elasticsearch
es = Elasticsearch()
print(es.ping())
```

* 環境 
```
$ java -version
java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)
```
```
$ python -V
Python 3.6.7
```
```
$ pip list | grep elasticsearch
elasticsearch       7.5.1
```

* エラー詳細
    * 500までカウントした後、以下のエラーが発生する。

```
Traceback (most recent call last):
File "/Users/ikunishi/.pyenv/versions/3.6.7/lib/python3.6/site-packages/urllib3/connectionpool.py", line 445, in _make_request
six.raise_from(e, None)
File "", line 3, in raise_from
File "/Users/ikunishi/.pyenv/versions/3.6.7/lib/python3.6/site-packages/urllib3/connectionpool.py", line 440, in _make_request
httplib_response = conn.getresponse()
File "/Users/ikunishi/.pyenv/versions/3.6.7/lib/python3.6/http/client.py", line 1331, in getresponse
response.begin()
File "/Users/ikunishi/.pyenv/versions/3.6.7/lib/python3.6/http/client.py", line 297, in begin
version, status, reason = self._read_status()
File "/Users/ikunishi/.pyenv/versions/3.6.7/lib/python3.6/http/client.py", line 258, in _read_status
line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
File "/Users/ikunishi/.pyenv/versions/3.6.7/lib/python3.6/socket.py", line 586, in readinto
return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Users/ikunishi/.pyenv/versions/3.6.7/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 246, in perform_request
method, url, body, retries=Retry(False), headers=request_headers, **kw
File "/Users/ikunishi/.pyenv/versions/3.6.7/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
File "/Users/ikunishi/.pyenv/versions/3.6.7/lib/python3.6/site-packages/urllib3/util/retry.py", line 506, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/Users/ikunishi/.pyenv/versions/3.6.7/lib/python3.6/site-packages/urllib3/packages/six.py", line 735, in reraise
raise value
File "/Users/ikunishi/.pyenv/versions/3.6.7/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
chunked=chunked,
File "/Users/ikunishi/.pyenv/versions/3.6.7/lib/python3.6/site-packages/urllib3/connectionpool.py", line 447, in _make_request
self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
File "/Users/ikunishi/.pyenv/versions/3.6.7/lib/python3.6/site-packages/urllib3/connectionpool.py", line 337, in _raise_timeout
self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=9200): Read timed out. (read timeout=20)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "insert.py", line 29, in
print(helpers.bulk(es, load(), chunk_size=500, request_timeout=20))
File "/Users/ikunishi/.pyenv/versions/3.6.7/lib/python3.6/site-packages/elasticsearch/helpers/actions.py", line 390, in bulk
for ok, item in streaming_bulk(client, actions, *args, **kwargs):
File "/Users/ikunishi/.pyenv/versions/3.6.7/lib/python3.6/site-packages/elasticsearch/helpers/actions.py", line 320, in streaming_bulk
**kwargs
File "/Users/ikunishi/.pyenv/versions/3.6.7/lib/python3.6/site-packages/elasticsearch/helpers/actions.py", line 247, in _process_bulk_chunk
for item in gen:
File "/Users/ikunishi/.pyenv/versions/3.6.7/lib/python3.6/site-packages/elasticsearch/helpers/actions.py", line 196, in _process_bulk_chunk_error
raise error
File "/Users/ikunishi/.pyenv/versions/3.6.7/lib/python3.6/site-packages/elasticsearch/helpers/actions.py", line 235, in _process_bulk_chunk
resp = client.bulk("\n".join(bulk_actions) + "\n", *args, **kwargs)
File "/Users/ikunishi/.pyenv/versions/3.6.7/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 152, in _wrapped
return func(*args, params=params, headers=headers, **kwargs)
File "/Users/ikunishi/.pyenv/versions/3.6.7/lib/python3.6/site-packages/elasticsearch/client/init.py", line 460, in bulk
body=body,
File "/Users/ikunishi/.pyenv/versions/3.6.7/lib/python3.6/site-packages/elasticsearch/transport.py", line 392, in perform_request
raise e
File "/Users/ikunishi/.pyenv/versions/3.6.7/lib/python3.6/site-packages/elasticsearch/transport.py", line 365, in perform_request
timeout=timeout,
File "/Users/ikunishi/.pyenv/versions/3.6.7/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 257, in perform_request
raise ConnectionTimeout("TIMEOUT", str(e), e)
elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='localhost', port=9200): Read timed out. (read timeout=20))
```

**Comment by ikuhiroo** [comment]
同様に、`ebdm_system.py` を実行すると、
```
elasticsearch.exceptions.TransportError: TransportError(503, 'cluster_block_exception', 'blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];')
```
が発生します。

**Comment by masahiro-mi** [comment]
PCの性能等にも依存するものと思いますが、elasticsearchのtimeoutをより長くすれば解決するかと思います。
`insert.py`の16行目を以下のように書き換えてみてください（同様にtimeoutが発生するようであれば、request_timeoutのパラメータをより大きく変更してください）
`print(helpers.bulk(es, load(), request_timeout=1000))`

`ebdm_system.py`のエラーに関しては、`insert.py`がうまく実行できていない故の不具合もあると思いますので、
`insert.py`の実行が成功したのち、より詳細なエラーについてご連絡いただけますと幸いです。

**Comment by ikuhiroo** [comment]
ありがとうございます。

デフォルトのポート9200で別ノードが起動しており、そのuuidが `_na_` となっていました。
ノードをもう一つ立ち上げ（ポート9203）、PythonコードのElasticsearchインスタンスを生成する箇所でポート指定を行うと、`insert.py' と `ebdm_system.py` ともに適切に処理をすることができました。

以下はcurlした結果です。
```
$ curl http://localhost:9200

{
  "name" : "node-0",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "_na_", <- ここが_na_になっていた
  "version" : {
    "number" : "7.5.1",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "3ae9ac9a93c95bd0cdc054951cf95d88e1e18d96",
    "build_date" : "2019-12-16T22:57:37.835892Z",
    "build_snapshot" : false,
    "lucene_version" : "8.3.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```
```
$ curl http://localhost:9203

{
  "name" : "node-1",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "C8MzhQMhSjeQiv74AYxyRw",
  "version" : {
    "number" : "7.10.0",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "51e9d6f22758d0374a0f3f5c6e8f3a7997850f96",
    "build_date" : "2020-11-09T21:30:33.964949Z",
    "build_snapshot" : false,
    "lucene_version" : "8.7.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
```

**Comment by ikuhiroo** [comment]
迅速な対応ありがとうございました🙇‍♂
