### ISSUE TITLE
ローカル環境でgenerative_system.py を実行するとRuntimeErrorが発生する

### ISSUE THREAD

**Issue by Kate47** [dsbook/dsbook#19]
dlg_model_step_100000.ptをGoogle Driveからローカルにコピーし,OpenNMT-pyをローカル環境にインストールしてからgenerative_system.pyを実行しました.プログラムの実行時にはエラーは発生しませんでしたが,Telegramで/startと入力してこちらの発話を入力するとRuntimeError: result type Float can't be cast to the desired output type Longが発生します.

**Comment by 1never** [comment]
こちらで新たな環境でやってみたのですが，エラーの再現ができません．
以下のコマンドでライブラリをインストールしたら動いたので，試していただけますでしょうか．

$ pip install --upgrade pip
$ pip install --upgrade setuptools
$ pip install torch==1.2.0+cpu torchvision==0.4.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
$ pip install python-telegram-bot==12.8
$ pip install mecab-python3==0.996.5

**Comment by Haruto388** [comment]
提示されたライブラリをそのコマンドのまま入力してgenerative_system.pyを起動したのですが，以下のようなエラー内容が出てきました．
```
Traceback (most recent call last):
  File "generative_system.py", line 1, in <module>
    from onmt.translate.translator import build_translator
  File "/usr/local/lib/python3.6/dist-packages/OpenNMT_py-0.9.2-py3.6.egg/onmt/__init__.py", line 4, in <module>
    import onmt.inputters
  File "/usr/local/lib/python3.6/dist-packages/OpenNMT_py-0.9.2-py3.6.egg/onmt/inputters/__init__.py", line 6, in <module>
    from onmt.inputters.inputter import \
  File "/usr/local/lib/python3.6/dist-packages/OpenNMT_py-0.9.2-py3.6.egg/onmt/inputters/inputter.py", line 11, in <module>
    import torchtext.data
  File "/home/inouelab/.local/lib/python3.6/site-packages/torchtext/__init__.py", line 6, in <module>
    from . import experimental
  File "/home/inouelab/.local/lib/python3.6/site-packages/torchtext/experimental/__init__.py", line 2, in <module>
    from . import transforms
  File "/home/inouelab/.local/lib/python3.6/site-packages/torchtext/experimental/transforms.py", line 4, in <module>
    from torchtext._torchtext import RegexTokenizer as RegexTokenizerPybind
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory
```

**Comment by 1never** [comment]
venvなどで新たな環境を作ってpipインストールから試していただけますでしょうか？
https://qiita.com/fiftystorm36/items/b2fd47cf32c7694adc2e

**Comment by Haruto388** [comment]
環境を新しく作ったらエラーが消えました．お手数おかけしました．
