### ISSUE TITLE
generative_system.pyがうまく動作しない

### ISSUE THREAD

**Issue by Haruto388** [dsbook/dsbook#20]
他の方のissuesにもあったのですがOpenNMTのデータからmodelを作成し，generative_system.pyを本の通りに起動し，Telegramで/startを打ち，対話を始めましょうと反応があり，対話を始めようとしたところ，以下のようなエラー文がコンソールに返ってきました．

```
/home/inouelab/.local/lib/python3.6/site-packages/onmt/translate/beam_search.py:161: UserWarning: An output with one or more elements was resized since it had shape [5], which does not match the required output shape [1, 5].This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  /pytorch/aten/src/ATen/native/Resize.cpp:19.)
  torch.mul(self.topk_scores, length_penalty, out=self.topk_log_probs)
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/inouelab/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 340, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/inouelab/.local/lib/python3.6/site-packages/telegram/ext/handler.py", line 122, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/home/inouelab/dsbook/telegram_bot.py", line 23, in message
    system_output = self.system.reply(input)
  File "generative_system.py", line 34, in reply
    attn_debug=False
  File "/home/inouelab/.local/lib/python3.6/site-packages/onmt/translate/translator.py", line 351, in translate
    batch, data.src_vocabs, attn_debug
  File "/home/inouelab/.local/lib/python3.6/site-packages/onmt/translate/translator.py", line 544, in translate_batch
    return_attention=attn_debug or self.replace_unk)
  File "/home/inouelab/.local/lib/python3.6/site-packages/onmt/translate/translator.py", line 695, in _translate_batch
    beam.advance(log_probs, attn)
  File "/home/inouelab/.local/lib/python3.6/site-packages/onmt/translate/beam_search.py", line 164, in advance
    torch.div(self.topk_ids, vocab_size, out=self._batch_index)
RuntimeError: result type Float can't be cast to the desired output type Long
```

実行環境：Ubuntu 18.04 LTS（Windows10）
                  Telegram version 2.4.7 

調べてみてもいまいちわからなかったのでここに書いてみました．申し訳ないのですが，確認のほどよろしくお願いいたします．

**Comment by 1never** [comment]
Colab上のOpenNMTのバージョンとローカルのバージョンが異なっている可能性があります．
最新のGitHubでは1.0.0rc1をColab上でインストールしていますので，ローカルでも

$pip install OpenNMT-py==1.0.0rc1

を実行してみてください．

**Comment by Haruto388** [comment]
お返事ありがとうございます．OpenNMT-pyを一度削除し新たに version 1.0.0rc1をインストールし，対話を試みましたがやはり同じエラー内容が表示されてしまいました．
そこでいろいろと試していると以下のようなエラー内容がGoogle Colobのlearn_generative_model.ipynbの一番最初のセルで流れていました．

```
ERROR: spacy 2.2.4 has requirement tqdm<5.0.0,>=4.38.0, but you'll have tqdm 4.30.0 which is incompatible.
ERROR: fbprophet 0.7.1 has requirement tqdm>=4.36.1, but you'll have tqdm 4.30.0 which is incompatible.
```

これ以外は特に不審なところは見当たりませんでした．
調べてみた感じこのエラーのせいでRuntimeErrorをはいてるように思われるのですが，対処法がよくわかりません．
申し訳ないのですが，確認のほどよろしくお願いします．

**Comment by 1never** [comment]
書いてあるとおりにtqdmのバージョンを上げれば良いと思います．

$ pip install tqdm==4.38.0

でいかがでしょう．

**Comment by Haruto388** [comment]
お返事ありがとうございます．言われた通り別のセルでバージョンアップを行いました．
```
!pip uninstall tqdm
!pip install tqdm==4.38.0
```

するとそのセルで以下のようなエラー文が出てきました．

```
  Successfully uninstalled tqdm-4.38.0
Collecting tqdm==4.38.0
  Using cached https://files.pythonhosted.org/packages/b9/08/8505f192efc72bfafec79655e1d8351d219e2b80b0dec4ae71f50934c17a/tqdm-4.38.0-py2.py3-none-any.whl
ERROR: opennmt-py 1.0.0rc1 has requirement tqdm~=4.30.0, but you'll have tqdm 4.38.0 which is incompatible.
Installing collected packages: tqdm
Successfully installed tqdm-4.38.0
```

tqdm自体はインストールできておりバージョンを確認しても特におかしい点は見つかりませんでした．

とりあえずlearn_generative_model.ipynbの一つ目のセルを実行してみるとエラーの内容が変わっていました．

```
ERROR: spacy 2.2.4 has requirement tqdm<5.0.0,>=4.38.0, but you'll have tqdm 4.30.0 which is incompatible.
ERROR: fbprophet 0.7.1 has requirement tqdm>=4.36.1, but you'll have tqdm 4.30.0 which is incompatible.
Installing collected packages: tqdm, torchtext
  Found existing installation: tqdm 4.38.0
    Uninstalling tqdm-4.38.0:
      Successfully uninstalled tqdm-4.38.0
  Found existing installation: torchtext 0.5.0
    Uninstalling torchtext-0.5.0:
      Successfully uninstalled torchtext-0.5.0
Successfully installed torchtext-0.4.0 tqdm-4.30.0
fatal: destination path 'OpenNMT-py' already exists and is not an empty directory.
```

以下にtqdmのバージョン詳細を乗っけます．

```
Name: tqdm
Version: 4.38.0
Summary: Fast, Extensible Progress Meter
Home-page: https://github.com/tqdm/tqdm
Author: None
Author-email: None
License: MPLv2.0, MIT Licences
Location: /usr/local/lib/python3.6/dist-packages
Requires: 
Required-by: torchtext, thinc, tensorflow-datasets, spacy, pymc3, panel, OpenNMT-py, moviepy, kaggle, hyperopt, gdown, fbprophet, fa2
```

**Comment by 1never** [comment]
ローカルのOpen-NMT-pyのバージョンは0.9.2にしてみてください．

$pip install OpenNMT-py==0.9.2

**Comment by Haruto388** [comment]
お返事ありがとうございます．
OpenNMT-pyはいったん削除し，バージョン0.9.2をローカルにインストールしたのですが相変わらずGoogle Colobのほうでエラーが出ました．
Google Colobのエラーについて検証してみたのでその結果をここに乗せてみます．
以下の文を実行したとき
```
!pip install torch==1.2.0+cu92 torchvision==0.4.0+cu92 -f https://download.pytorch.org/whl/torch_stable.html
!pip install torchtext==0.5 configargparse
!pip install OpenNMT-py==1.0.0
!git clone https://github.com/OpenNMT/OpenNMT-py.git -b 0.9.2
```
以下のエラーが出ます．
```
ERROR: spacy 2.2.4 has requirement tqdm<5.0.0,>=4.38.0, but you'll have tqdm 4.30.0 which is incompatible.
ERROR: fbprophet 0.7.1 has requirement tqdm>=4.36.1, but you'll have tqdm 4.30.0 which is incompatible.
```
なので次に以下のようにして実行してみました．
```
!pip install torch==1.2.0+cu92 torchvision==0.4.0+cu92 -f https://download.pytorch.org/whl/torch_stable.html
!pip install torchtext==0.5 configargparse
!pip uninstall tqdm
!pip install tqdm==4.38.0
!pip install OpenNMT-py==1.0.0
!git clone https://github.com/OpenNMT/OpenNMT-py.git -b 0.9.2
```
すると先ほどと全く同じエラーが返ってきました．

解決策がわかりません．確認のほどお願いいたします．

**Comment by 1never** [comment]
Duplicate of #19
