### ISSUE TITLE
generative_system.pyでRuntimeErrorが発生する

### ISSUE THREAD

**Issue by yashinom1** [dsbook/dsbook#22]
generative_systemで対話を始めるところまではできるのですが、文字を入力すると下のようなエラーが出ます。
`/usr/local/lib/python3.6/dist-packages/OpenNMT_py-0.9.2-py3.6.egg/onmt/translate/beam_search.py:161: UserWarning: An output with one or more elements was resized since it had shape [5], which does not match the required output shape [1, 5].This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  /pytorch/aten/src/ATen/native/Resize.cpp:19.)
  torch.mul(self.topk_scores, length_penalty, out=self.topk_log_probs)
Traceback (most recent call last):
  File "generative_system.py", line 46, in <module>
    bot.run()
  File "/home/yorihime/dsbook/console_bot.py", line 28, in run
    sys_out = self.message(input_utt)
  File "/home/yorihime/dsbook/console_bot.py", line 17, in message
    system_output = self.system.reply(input)
  File "generative_system.py", line 35, in reply
    attn_debug=False
  File "/usr/local/lib/python3.6/dist-packages/OpenNMT_py-0.9.2-py3.6.egg/onmt/translate/translator.py", line 351, in translate
    batch, data.src_vocabs, attn_debug
  File "/usr/local/lib/python3.6/dist-packages/OpenNMT_py-0.9.2-py3.6.egg/onmt/translate/translator.py", line 544, in translate_batch
    return_attention=attn_debug or self.replace_unk)
  File "/usr/local/lib/python3.6/dist-packages/OpenNMT_py-0.9.2-py3.6.egg/onmt/translate/translator.py", line 695, in _translate_batch
    beam.advance(log_probs, attn)
  File "/usr/local/lib/python3.6/dist-packages/OpenNMT_py-0.9.2-py3.6.egg/onmt/translate/beam_search.py", line 164, in advance
    torch.div(self.topk_ids, vocab_size, out=self._batch_index)
RuntimeError: result type Float can't be cast to the desired output type Long`

同じような質問されてた方のissueを見て、ローカルのOpenNMTのバージョンを1.0.0rc1にしたり、tqdmのバージョンを4.38.0にしたり、Telegramを使用せずに対話システムを実行可能にしてみたりしたのですが同じエラーが発生します。
調べても解決策が分からなかったので、ここで質問させていただきます。
確認よろしくお願いします。

実行環境：Ubuntu 18.04 LTS

**Comment by 1never** [comment]
こちらで新たな環境でやってみたのですが，エラーの再現ができません．
以下のコマンドでライブラリをインストールしたら動いたので，試していただけますでしょうか．

$ pip install --upgrade pip
$ pip install --upgrade setuptools
$ pip install torch==1.2.0+cpu torchvision==0.4.0+cpu -f https://download.pytorch.org/whl/torch_stable.html  
$ pip install python-telegram-bot==12.8  
$ pip install mecab-python3==0.996.5    

# 実行
$ python generative_system.py --model dlg_model_step_1000.pt -replace_unk -src None

**Comment by 1never** [comment]
Duplicate of #19
