### ISSUE TITLE
train_da_model.pyの実行時にエラーが出る

### ISSUE THREAD

**Issue by HK234** [dsbook/dsbook#28]
generate_da_samples.py で examples.txt から da_samples.dat を作成し train_da_model.py で学習させようとしたところ以下のようなエラーが出ます。

File "train_da_model.py", line 25, in <module>
    word, feature_str = line.split('\t')
ValueError: too many values to unpack (expected 2)

このような場合どのようにすればよいか教えていただけると幸いです。

**Comment by 1never** [comment]
タブが入っていない行をsplitしているエラーです．
ファイルに空行やタブが入っていない行がないか確認をお願いします．

**Comment by 1never** [comment]
mecab-python3のバージョンを下げてください．
以下をインストールすれば動きます．

$pip install mecab-python3==0.996.5

**Comment by cyacyamomonini** [comment]
$pip install mecab-python3==0.996.5で以下のエラーです。解決方法をご教示ください。
(base) ryo@LAPTOP-AA4DN0VR:~$ pip install mecab-python3==0.996.5
Collecting mecab-python3==0.996.5
  Downloading mecab-python3-0.996.5.tar.gz (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.6/65.6 kB 3.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      /home/ryo/anaconda3/lib/python3.9/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      running egg_info
      creating /tmp/pip-pip-egg-info-6nwkuo0p/mecab_python3.egg-info
      writing /tmp/pip-pip-egg-info-6nwkuo0p/mecab_python3.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-6nwkuo0p/mecab_python3.egg-info/dependency_links.txt
      writing top-level names to /tmp/pip-pip-egg-info-6nwkuo0p/mecab_python3.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-6nwkuo0p/mecab_python3.egg-info/SOURCES.txt'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-q0fctjbb/mecab-python3_b4d2a7f0e34646c5aade7d9c990aa2f3/setup.py", line 237, in <module>
          setup(name = "mecab-python3",
        File "/home/ryo/anaconda3/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/ryo/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/ryo/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/ryo/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
          self.run_command(cmd)
        File "/home/ryo/anaconda3/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/home/ryo/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/home/ryo/anaconda3/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 307, in run
          self.find_sources()
        File "/home/ryo/anaconda3/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 314, in find_sources
          mm.run()
        File "/home/ryo/anaconda3/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 549, in run
          self.add_defaults()
        File "/home/ryo/anaconda3/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 586, in add_defaults
          sdist.add_defaults(self)
        File "/home/ryo/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/command/sdist.py", line 250, in add_defaults
          self._add_defaults_python()
        File "/home/ryo/anaconda3/lib/python3.9/site-packages/setuptools/command/sdist.py", line 113, in _add_defaults_python
          self._add_data_files(self._safe_data_files(build_py))
        File "/home/ryo/anaconda3/lib/python3.9/site-packages/setuptools/command/sdist.py", line 132, in _add_data_files
          self.filelist.extend(
        File "/home/ryo/anaconda3/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 497, in extend
          self.files.extend(filter(self._safe_path, paths))
        File "/home/ryo/anaconda3/lib/python3.9/site-packages/setuptools/command/sdist.py", line 134, in <genexpr>
          for _, src_dir, _, filenames in data_files
      ValueError: not enough values to unpack (expected 4, got 1)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
