### ISSUE TITLE
P27 BotFatherで発行したアクセストークンを使ってもInvalid Tokenと表示されます

### ISSUE THREAD

**Issue by general-liebe** [dsbook/dsbook#33]
MacOSユーザーです。対話システムに興味があって本書籍を購入いたしました。初心者で拙い質問になっているかもしれませんがよろしくお願いいたします。

事前にtelegram_bot.pyのTOKEN=""の部分はBotFatherで発行したアクセストークンに書き換えた上，Readme.mdの「Telegramから応答が返ってこない 」の部分に従いpython-telegram-botのバージョンを12.8に指定しておりますが，dsbook上で
~$python3 echo_system.pyを実行すると，

Traceback (most recent call last):
  File "echo_system.py", line 19, in <module>
    bot.run()
  File "/Users/###/dsbook/telegram_bot.py", line 29, in run
    updater = Updater('TOKEN')
  File "/Users/###/anaconda3/lib/python3.7/site-packages/telegram/ext/updater.py", line 165, in __init__
    defaults=defaults)
  File "/Users/###/anaconda3/lib/python3.7/site-packages/telegram/bot.py", line 130, in __init__
    self.token = self._validate_token(token)
  File "/Users/###/anaconda3/lib/python3.7/site-packages/telegram/bot.py", line 197, in _validate_token
    raise InvalidToken()
telegram.error.InvalidToken: Invalid token

という表示がされます。

アクセストークンは何回かコピーし直してプログラムの再実行を行いましたため，アクセストークンのコピーに問題があるわけではないと思います。

よろしくお願いいたします。

**Comment by masahiro-mi** [comment]
Mac OS Big Sur バージョン11.5.2にて検証を行いました。
python-telegram-botのバージョンは12.8で、新たにTelegramのインストール・Botの作成、アクセストークンの発行を行い、
telegram_bot.pyのTOKEN=""に記入して
$ python3 echo_system.py
を実行したところ、我々の環境では正しく動作しました。

加えて、適当に間違えたアクセストークンをtelegram_bot.pyのTOKEN=""に記入して実行した場合、報告されている内容と同様のエラーが出ることも確認しました。
おそらく、アクセストークンをコピーする際に先頭や最後の文字が抜けている（選択できていなかった）か、なんらかの理由でBotFatherから発行されたトークンが無効化されている可能性があります。
以下の処理を行ってみてください。
1. BotFatherに /mybots とメッセージを送り、アクセストークンを再発行したいbotを選択し、API Tokenのボタンを押してアクセストークンを再度確認してください。
2. アクセストークン全体をコピーして、プログラムに貼り付けてください。
3. BotFatherから出ているアクセストークンと、プログラムに貼り付けたアクセストークンの桁数、文字、記号が全て同じかどうか二つ並べてご確認ください。
