### ISSUE TITLE
P165 bert_ebdm_system.pyのエラーについて

### ISSUE THREAD

**Issue by xxxxtakajunxxxx** [dsbook/dsbook#36]
bert_evaluator.binを配置し、
P165のbert_ebdm_system.pyを実行したところ、下記のエラーが発生しました。
(私の環境のコンソールをそのまま記載します)
-----------------------------------------------------------------------
root@fae3262985d1:~/dsbook/dsbook# python3 bert_ebdm_system.py
Traceback (most recent call last):
  File "bert_ebdm_system.py", line 36, in <module>
    system = BertEbdmSystem()
  File "bert_ebdm_system.py", line 9, in __init__
    self.evaluator = BertEvaluator()
  File "/root/dsbook/dsbook/bert_evaluator.py", line 11, in __init__
    self.model = BertForSequenceClassification.from_pretrained("bert-base-multilingual-cased", num_labels=2)
  File "/usr/local/lib/python3.8/dist-packages/transformers/modeling_utils.py", line 345, in from_pretrained
    state_dict = torch.load(resolved_archive_file, map_location='cpu')
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 794, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 1613741 more bytes. The file might be corrupted.
root@fae3262985d1:~/dsbook/dsbook#
-----------------------------------------------------------------------
google colabのbert_example_based_finetuning.ipynbも特にエラーは発生しておらず、pytorch_model.binをダウンロードしました。
原因、対処方法がわかりません。

**Comment by xxxxtakajunxxxx** [comment]
pytorch_model.binを再作成して、ダウンロードしたところ解消しました。
