### ISSUE TITLE
エラーが出ます。

### ISSUE THREAD

**Issue by Maimikuru** [dsbook/dsbook#39]
2種類のエラーが出ました。

$python3 da_extractor.py
Traceback (most recent call last):
  File "da_extractor.py", line 12, in <module>
    vectorizer = dill.load(f)
  File "/home/mai/.local/lib/python3.8/site-packages/dill/_dill.py", line 313, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/home/mai/.local/lib/python3.8/site-packages/dill/_dill.py", line 525, in load
    obj = StockUnpickler.load(self)
TypeError: an integer is required (got type bytes)

$ python3 frame_weather_system.py
Traceback (most recent call last):
  File "frame_weather_system.py", line 181, in <module>
    system = FrameWeatherSystem()
  File "frame_weather_system.py", line 52, in __init__
    self.da_concept = DA_Concept()
  File "/home/mai/dsbook/da_concept_extractor.py", line 21, in __init__
    self.vectorizer = dill.load(f)
  File "/home/mai/.local/lib/python3.8/site-packages/dill/_dill.py", line 313, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/home/mai/.local/lib/python3.8/site-packages/dill/_dill.py", line 525, in load
    obj = StockUnpickler.load(self)
TypeError: an integer is required (got type bytes)

$ python3 generate_concept_samples.py
Traceback (most recent call last):
  File "generate_concept_samples.py", line 89, in <module>
    word, feature_str = line.split("\t")
ValueError: too many values to unpack (expected 2)

$ python3 train_da_model.py
Traceback (most recent call last):
  File "train_da_model.py", line 25, in <module>
    word, feature_str = line.split("\t")
ValueError: too many values to unpack (expected 2)

よろしくお願いいたします。

**Comment by Maimikuru** [comment]
バグについて書きましたが、この本の筆者様から何の回答も得られませんでした。この本を読んでいる方で、da_extractor.pyと train_da_model.pyでエラーが出てくる方は、以下のコードに書き換えてください。

da_extractor.pyの19行目から23行目
train_da_model.pyの20行目から25行目

for word in mecab.parse(utt).splitlines():
        if word == "EOS":
            break
        else:
            words.append(word)

**Comment by Maimikuru** [comment]
また、generate_concept_sample.pyなどでもバグがでてくるとおもいます。コードを見ると、featureにアクセスして、その0番目の情報を得ることが目的なのに、featureにアクセスしていないことが原因です。

generate_concept_sample.pyの89行目からを以下のコードに書き換えてください。

word= line.split("\t")
                    t = MeCab.Tagger()
                    node = t.parseToNode(word[0])
                    postag = node.next.feature.split(',')[0]
                    # 現在の文字位置に対応するタグを取得
                    label = get_label(pos, posdic)
                    # label がOでなく，直前のラベルと同じであればラベルに'I-'をつける
                    if label == "O":
                        lis.append([word[0], postag, "O"])
                    elif label == prev_label:
                        lis.append([word[0], postag, "I-" + label])
                    else:
                        lis.append([word[0], postag, "B-" + label])
                    pos += len(word[0])
                    prev_label = label
            
            # 単語，品詞，ラベルを学習用ファイルに書き出す
            for word, postag, label in lis:
                fp.write(word + "\t" + postag + "\t" + label + "\n")
            fp.write("\n")

fp.close()
