### ISSUE TITLE
P27 でtelegram.error.Unauthorized: Unauthorizedと表示されます

### ISSUE THREAD

**Issue by takada16576** [dsbook/dsbook#49]
WSL2のUbuntu20.04.6LTSを利用して実行しました。
BotFatherで発行したアクセストークンは認識しているようなのですが、以下のようにtelegram.error.Unauthorized: Unauthorizedと表示されます。

$ python3 echo_system.py
/home/xxxx/dsbook/telegram_bot.py:31: TelegramDeprecationWarning: Old Handler API is deprecated - see https://git.io/fxJuV for details
  updater = Updater(TOKEN)
Traceback (most recent call last):
  File "echo_system.py", line 19, in <module>
    bot.run()
  File "/home/xxxx/dsbook/telegram_bot.py", line 36, in run
    updater.start_polling()
  File "/home/xxxx/.local/lib/python3.8/site-packages/telegram/ext/updater.py", line 259, in start_polling
    self.job_queue.start()
  File "/home/xxxx/.local/lib/python3.8/site-packages/telegram/ext/jobqueue.py", line 446, in start
    name="Bot:{}:job_queue".format(self._dispatcher.bot.id))
  File "/home/xxxx/.local/lib/python3.8/site-packages/telegram/bot.py", line 51, in decorator
    self.get_me()
  File "/home/xxxx/.local/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/xxxx/.local/lib/python3.8/site-packages/telegram/bot.py", line 67, in decorator
    result = func(*args, **kwargs)
  File "/home/xxxx/.local/lib/python3.8/site-packages/telegram/bot.py", line 289, in get_me
    result = self._request.get(url, timeout=timeout)
  File "/home/xxxx/.local/lib/python3.8/site-packages/telegram/utils/request.py", line 276, in get
    result = self._request_wrapper('GET', url, **urlopen_kwargs)
  File "/home/xxxx/.local/lib/python3.8/site-packages/telegram/utils/request.py", line 242, in _request_wrapper
    raise Unauthorized(message)
telegram.error.Unauthorized: Unauthorized

以上、よろしくお願いいたします。

**Comment by 1never** [comment]
Unauthorizedとは認証できないということですので，トークンが間違っている可能性があります．合っているかどうかのチェックをお願いします．

**Comment by takada16576** [comment]
早速の回答ありがとうございます。

トークンのコピーで1文字間違っていました。
修正後のテストでＯＫになりました。

単純なミスで申し訳ありませんでした。

以上、よろしくお願いします。


2023年9月11日(月) 13:09 Michimasa Inaba ***@***.***>:

**Comment by takada16576** [comment]
解決済です。
