### ISSUE TITLE
P165で、Your PyTorch installation may be too old. となってしまいました

### ISSUE THREAD

**Issue by takada16576** [dsbook/dsbook#50]
2023年9月時点のColabでは" !pip install torch==1.4.0+cu92 torchvision==0.5.0+cu92 "がエラーになります。
現時点のColabで変更可能なCUDAは"CUDA 11, CUDA 11.8"のようですが、CUDA 9.2のインストールが必要なのでしょうか？

アドバイスをいただければ幸いです。

(1) P165で、"Your PyTorch installation may be too old." となってしまい、bert_ebdm_system.pyが動作しませんでした。
$ python3 bert_ebdm_system.py
Traceback (most recent call last):
  File "bert_ebdm_system.py", line 36, in <module>
    system = BertEbdmSystem()
  File "bert_ebdm_system.py", line 9, in __init__
    self.evaluator = BertEvaluator()
  File "/home/xxxx/dsbook/bert_evaluator.py", line 13, in __init__
    self.model.load_state_dict(torch.load("bert_evaluator.bin", map_location='cpu'))
  File "/home/xxxx/.local/lib/python3.8/site-packages/torch/serialization.py", line 527, in load
    with _open_zipfile_reader(f) as opened_zipfile:
  File "/home/xxxx/.local/lib/python3.8/site-packages/torch/serialization.py", line 224, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /pytorch/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at /pytorch/caffe2/serialize/inline_container.cc:132)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7ff46eeb1193 in /home/xxxx/.local/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: caffe2::serialize::PyTorchStreamReader::init() + 0x1f5b (0x7ff471001f8b in /home/xxxx/.local/lib/python3.8/site-packages/torch/lib/libtorch.so)
frame #2: caffe2::serialize::PyTorchStreamReader::PyTorchStreamReader(std::string const&) + 0x64 (0x7ff4710031a4 in /home/xxxx/.local/lib/python3.8/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x68a336 (0x7ff47e6ad336 in /home/xxxx/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x26ffa7 (0x7ff47e292fa7 in /home/xxxx/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #7: python3() [0x50b8a8]
frame #9: python3() [0x59cbb0]
frame #13: python3() [0x59c396]
frame #19: python3() [0x59c26b]
frame #22: python3() [0x59c26b]
frame #27: python3() [0x67dbf1]
frame #28: python3() [0x67dc6f]
frame #29: python3() [0x67dd11]
frame #33: __libc_start_main + 0xf3 (0x7ff48b832083 in /lib/x86_64-linux-gnu/libc.so.6)

(2) P158で、colabのBERT_example_based_finetuning.ipynbでエラーが出ていました。
----------------------------------------------------------------------------
!pip install torch==1.4.0+cu92 torchvision==0.5.0+cu92 torchaudio==0.4.0 torchtext==0.5.0 folium==0.2.1 -f https://download.pytorch.org/whl/torch_stable.html
-----------------------------------------------------------------------------
Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch==1.4.0+cu92 (from versions: 1.11.0, 1.11.0+cpu, 1.11.0+cu102, 1.11.0+cu113, 1.11.0+cu115, 1.11.0+rocm4.3.1, 1.11.0+rocm4.5.2, 1.12.0, 1.12.0+cpu, 1.12.0+cu102, 1.12.0+cu113, 1.12.0+cu116, 1.12.0+rocm5.0, 1.12.0+rocm5.1.1, 1.12.1, 1.12.1+cpu, 1.12.1+cu102, 1.12.1+cu113, 1.12.1+cu116, 1.12.1+rocm5.0, 1.12.1+rocm5.1.1, 1.13.0, 1.13.0+cpu, 1.13.0+cu116, 1.13.0+cu117, 1.13.0+cu117.with.pypi.cudnn, 1.13.0+rocm5.1.1, 1.13.0+rocm5.2, 1.13.1, 1.13.1+cpu, 1.13.1+cu116, 1.13.1+cu117, 1.13.1+cu117.with.pypi.cudnn, 1.13.1+rocm5.1.1, 1.13.1+rocm5.2, 2.0.0, 2.0.0+cpu, 2.0.0+cpu.cxx11.abi, 2.0.0+cu117, 2.0.0+cu117.with.pypi.cudnn, 2.0.0+cu118, 2.0.0+rocm5.3, 2.0.0+rocm5.4.2, 2.0.1, 2.0.1+cpu, 2.0.1+cpu.cxx11.abi, 2.0.1+cu117, 2.0.1+cu117.with.pypi.cudnn, 2.0.1+cu118, 2.0.1+rocm5.3, 2.0.1+rocm5.4.2)
ERROR: No matching distribution found for torch==1.4.0+cu92

(3) Colabの変更可能なCUDAの確認
------------------------------------
!ls -d /usr/local/cuda-*
!which nvcc
-------------------------------------
/usr/local/cuda-11  /usr/local/cuda-11.8
/usr/local/cuda/bin/nvcc

以上、よろしくお願い申し上げます

**Comment by takada16576** [comment]
2023年9月時点のColabでは、Ubuntu22.04のようなので、CUDA 9.2のインストールは難しそうです。
Colab利用は断念し、GPU付きのローカルPCでの実施をしていきたいと思います。

!cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
