### ISSUE TITLE
python3 bert_ebdm_system.pyを実行しても動きません

### ISSUE THREAD

**Issue by osuro33** [dsbook/dsbook#8]
いろいろ試してみたのですが解決方法がわかりません。ご助力いただけると幸いです。
$ python3 bert_ebdm_system.py
Traceback (most recent call last):
  File "/usr/lib/python3.6/tarfile.py", line 189, in nti
    n = int(s.strip() or "0", 8)
ValueError: invalid literal for int() with base 8: 'h._utils'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/tarfile.py", line 2299, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib/python3.6/tarfile.py", line 1093, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "/usr/lib/python3.6/tarfile.py", line 1035, in frombuf
    chksum = nti(buf[148:156])
  File "/usr/lib/python3.6/tarfile.py", line 191, in nti
    raise InvalidHeaderError("invalid header")
tarfile.InvalidHeaderError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/osuro/.local/lib/python3.6/site-packages/torch/serialization.py", line 555, in _load
    return legacy_load(f)
  File "/home/osuro/.local/lib/python3.6/site-packages/torch/serialization.py", line 466, in legacy_load
    with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT)) as tar, \
  File "/usr/lib/python3.6/tarfile.py", line 1591, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib/python3.6/tarfile.py", line 1621, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/lib/python3.6/tarfile.py", line 1484, in __init__
    self.firstmember = self.next()
  File "/usr/lib/python3.6/tarfile.py", line 2311, in next
    raise ReadError(str(e))
tarfile.ReadError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bert_ebdm_system.py", line 36, in <module>
    system = BertEbdmSystem()
  File "bert_ebdm_system.py", line 9, in __init__
    self.evaluator = BertEvaluator()
  File "/home/osuro/dsbook/bert_evaluator.py", line 13, in __init__
    self.model.load_state_dict(torch.load("bert_evaluator.bin", map_location='cpu'))
  File "/home/osuro/.local/lib/python3.6/site-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/osuro/.local/lib/python3.6/site-packages/torch/serialization.py", line 559, in _load
    raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
RuntimeError: bert_evaluator.bin is a zip archive (did you mean to use torch.jit.load()?)

**Comment by 1never** [comment]
bert_evaluator.binがzipファイルだというエラーが出ています．Google Driveから複数のファイルをダウンロードするとzip圧縮されますので，そこに問題があるのではと思います．
