### ISSUE TITLE
python3 bert_ebdm_system.py　について

### ISSUE THREAD

**Issue by osuro33** [dsbook/dsbook#9]
前回の質問は間違えてとじてしまったのでもう一度質問させていただきます。zipフファイルについて問題があったので展開してからダウンロードしてみたり、ファイルの名前を変えてみたりしましたが問題解決しませんでした。ほかに問題がないかアドバイスをお願いします。
k$ python3 bert_ebdm_system.py
Traceback (most recent call last):
  File "/usr/lib/python3.6/tarfile.py", line 189, in nti
    n = int(s.strip() or "0", 8)
ValueError: invalid literal for int() with base 8: 'h._utils'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/tarfile.py", line 2299, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib/python3.6/tarfile.py", line 1093, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "/usr/lib/python3.6/tarfile.py", line 1035, in frombuf
    chksum = nti(buf[148:156])
  File "/usr/lib/python3.6/tarfile.py", line 191, in nti
    raise InvalidHeaderError("invalid header")
tarfile.InvalidHeaderError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/osuro/.local/lib/python3.6/site-packages/torch/serialization.py", line 555, in _load
    return legacy_load(f)
  File "/home/osuro/.local/lib/python3.6/site-packages/torch/serialization.py", line 466, in legacy_load
    with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT)) as tar, \
  File "/usr/lib/python3.6/tarfile.py", line 1591, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib/python3.6/tarfile.py", line 1621, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/lib/python3.6/tarfile.py", line 1484, in __init__
    self.firstmember = self.next()
  File "/usr/lib/python3.6/tarfile.py", line 2311, in next
    raise ReadError(str(e))
tarfile.ReadError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bert_ebdm_system.py", line 36, in <module>
    system = BertEbdmSystem()
  File "bert_ebdm_system.py", line 9, in __init__
    self.evaluator = BertEvaluator()
  File "/home/osuro/dsbook/bert_evaluator.py", line 13, in __init__
    self.model.load_state_dict(torch.load("bert_evaluator.bin", map_location='cpu'))
  File "/home/osuro/.local/lib/python3.6/site-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/osuro/.local/lib/python3.6/site-packages/torch/serialization.py", line 559, in _load
    raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
RuntimeError: bert_evaluator.bin is a zip archive (did you mean to use torch.jit.load()?)

**Comment by 1never** [comment]
ColabのPyTorchのバージョンが上がったためエラーが出たようです．
GitHub上のbert_example_based_finetuning.ipynbを動くように更新しましたので，そちらを使って再度試してみてください．

**Comment by osuro33** [comment]
再ダウンロードして実行してみましたが解決しませんでした。やり方が違うのでしょうか？

**Comment by 1never** [comment]
修正が必要なのはbert_ebdm_system.pyではなく，bert_example_based_finetuning.ipynbです．
Google Colab上で再度学習した上でダウンロードが必要ですので，そちらを試していただけますか？

**Comment by osuro33** [comment]
学習させてダウンロードしましたが出来ませんでした。出る表示は変わりませんでした。

**Comment by 1never** [comment]
こちらでもRuntimeError: bert_evaluator.bin is a zip archive (did you mean to use torch.jit.load()?)が出るのを確認し，bert_example_based_finetuning.ipynbを修正したら正しく動いたのですが．

確認のため，コンソールで以下を実行した結果を確認し，torchが1.2.0，transformers が 2.1.1のバージョンとなっているかをご確認いただけますでしょうか．
$pip3 list

**Comment by osuro33** [comment]
バージョンの確認をしてみましたが変わらないように見えます。その他のバージョンが違っていたら教えていただけると助かります。ご確認お願いします。
$ pip3 list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
asn1crypto (0.24.0)
attrs (17.4.0)
Automat (0.6.0)
blinker (1.4)
boto (2.49.0)
boto3 (1.14.43)
botocore (1.17.43)
certifi (2020.6.20)
cffi (1.14.1)
chardet (3.0.4)
click (7.1.2)
cloud-init (19.4)
colorama (0.3.7)
command-not-found (0.3)
configobj (5.0.6)
constantly (15.1.0)
cryptography (3.0)
decorator (4.4.2)
dill (0.3.2)
distro-info (0.18ubuntu0.18.04.1)
docutils (0.15.2)
elasticsearch (7.8.1)
gensim (3.8.3)
httplib2 (0.9.2)
hyperlink (17.3.1)
idna (2.10)
incremental (16.10.1)
Jinja2 (2.10)
jmespath (0.10.0)
joblib (0.16.0)
jsonpatch (1.16)
jsonpointer (1.10)
jsonschema (2.6.0)
keyring (10.6.0)
keyrings.alt (3.0)
language-selector (0.1)
MarkupSafe (1.0)
mecab-python3 (1.0.1)
netifaces (0.10.4)
numpy (1.19.1)
oauthlib (2.0.6)
PAM (0.4.2)
Pillow (7.2.0)
pip (9.0.1)
protobuf (3.12.4)
pyasn1 (0.4.2)
pyasn1-modules (0.2.1)
pycparser (2.20)
pycrypto (2.6.1)
pyemd (0.5.1)
pygobject (3.26.1)
PyJWT (1.5.3)
pyOpenSSL (17.5.0)
pyserial (3.4)
python-aiml (0.9.3)
python-apt (1.6.5+ubuntu0.2)
python-dateutil (2.8.1)
python-debian (0.1.32)
python-Levenshtein (0.12.0)
python-telegram-bot (12.8)
pyxdg (0.25)
PyYAML (3.12)
regex (2020.7.14)
requests (2.24.0)
requests-unixsocket (0.1.5)
s3transfer (0.3.3)
sacremoses (0.0.43)
scikit-learn (0.23.2)
scipy (1.5.2)
SecretStorage (2.3.1)
sentencepiece (0.1.92)
service-identity (16.0.0)
setuptools (49.3.1)
six (1.15.0)
sklearn (0.0)
smart-open (2.1.0)
ssh-import-id (5.7)
systemd-python (234)
tensorboardX (1.9)
threadpoolctl (2.1.0)
torch (1.2.0+cpu)
torchvision (0.4.0+cpu)
tornado (6.0.4)
tqdm (4.48.2)
transformers (2.1.1)
Twisted (17.9.0)
ufw (0.36)
unattended-upgrades (0.1)
unidic-lite (1.0.6)
urllib3 (1.25.10)
wheel (0.30.0)
zope.interface (4.3.2)

**Comment by 1never** [comment]
こちらでもバージョンを合わせましたが，こちらでは動いています．
以下からこちらで学習した学習済みファイルをダウンロードし，試しに動かしてもらえますか？
https://drive.google.com/file/d/1-pz7Mr5XQMeQyszcC4qt8POEKiiLadjX/view?usp=sharing

**Comment by osuro33** [comment]
頂いたファイルのおかげでプログラムは動きました。ありがとうございます。しかし、テレグラムに話しかけても返事がなく何か問題があるそうなのですが原因がわかりません。
$ python3 bert_ebdm_system.py
/home/osuro/dsbook/telegram_bot.py:29: TelegramDeprecationWarning: Old Handler API is deprecated - see https://git.io/fxJuV for details
  updater = Updater(TOKEN)
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/osuro/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 340, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/osuro/.local/lib/python3.6/site-packages/telegram/ext/handler.py", line 122, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/home/osuro/dsbook/telegram_bot.py", line 23, in message
    system_output = self.system.reply(input)
  File "bert_ebdm_system.py", line 18, in reply
    for r in self.__reply(input['utt']):
  File "bert_ebdm_system.py", line 28, in __reply
    body={'query':{'match':{'query':utt}}, 'size':10,})
  File "/home/osuro/.local/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 139, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/home/osuro/.local/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 1484, in search
    body=body,
  File "/home/osuro/.local/lib/python3.6/site-packages/elasticsearch/transport.py", line 352, in perform_request
    timeout=timeout,
  File "/home/osuro/.local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 256, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/osuro/.local/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 288, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [dialogue_pair]', dialogue_pair, index_or_alias)

**Comment by 1never** [comment]
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [dialogue_pair]', dialogue_pair, index_or_alias)
と書いてあるので，elasticsearchのエラーです．elasticsearchにデータが入っていないのだと思います．
まずはそのあたりを確認し，BERTを使用しないebdm_system.pyが正しく動くことを確認してください．

**Comment by osuro33** [comment]
ebdm_system.pyを実行してみたところ動きませんでした。前回実行した時は正常に動いていました。

**Comment by osuro33** [comment]
結果はこちらです。
$ python3 ebdm_system.py
/home/osuro/dsbook/telegram_bot.py:29: TelegramDeprecationWarning: Old Handler API is deprecated - see https://git.io/fxJuV for details
  updater = Updater(TOKEN)
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/osuro/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 340, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/osuro/.local/lib/python3.6/site-packages/telegram/ext/handler.py", line 122, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/home/osuro/dsbook/telegram_bot.py", line 23, in message
    system_output = self.system.reply(input)
  File "ebdm_system.py", line 49, in reply
    for r in self.__reply(input['utt']):
  File "ebdm_system.py", line 58, in __reply
    body={'query':{'match':{'query':utt}}, 'size':100,})
  File "/home/osuro/.local/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 139, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/home/osuro/.local/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 1484, in search
    body=body,
  File "/home/osuro/.local/lib/python3.6/site-packages/elasticsearch/transport.py", line 352, in perform_request
    timeout=timeout,
  File "/home/osuro/.local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 256, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/osuro/.local/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 288, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [dialogue_pair]', dialogue_pair, index_or_alias)

**Comment by 1never** [comment]
Elasiticsearchの起動やデータのインサートがきちんとできているかを確認していただければ動くと思いますので，まずは書籍を参照してその確認をお願いします．

**Comment by osuro33** [comment]
解決しました。無事会話をすることが出来ました。何度も質問に答えて頂きありがとうございました。
